# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da2ebaa598d84c5ec60d258b85ce5b97d53752ac9fc367616c77070120916f8de40571522be0d3ed8fd95d44067722950fdf416643d3cf86e344866cead139b4

test:
  secret_key_base: 75b6af1ba63957c7a5b5d7f41004efc0433be21f4f4cbe840901d4fe621cbc3836d648d5ded847a2dbf44b29dd52961714982cc7f926cecad8056e31eee681c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
